### ISSUE TITLE
Grafica tileset

### ISSUE THREAD

**Issue by Seiseisei666** [Seiseisei666/Quantum#12]
- Ora che abbiamo lo sfondo sarebbe il caso di avere le caselle trasparenti! (:
- Vogliamo fare delle animazioni? Se sì, quali?

**Comment by kAtoblepO** [comment]
Direi che questo si può chiudere per 2 motivi:
- include 2 issues
- il primo è già stato fatto e per il secondo ho fatto il milestone

**Comment by Seiseisei666** [comment]
Ok, passo e chiudo!
